### ISSUE TITLE
How to test?

### ISSUE THREAD

**Issue by IonicaBizau** [Maneevao/OS#1]
How can I test this little app?

**Comment by Maneevao** [comment]
It's a very little application. If you wanna know about OS development, I recommend you osdev.org.
You will be able to develop a more complicated system.

I just figure out how to use github.

You can compile application with command:
nasm -fbin -o boot.img code.asm
To run:
qemu -fda boot.img
To exit:
"ctrl+alt+2", command: "q"

**Comment by IonicaBizau** [comment]
Thanks! Everything worked fine.

What are the commands I can run?

**Comment by Maneevao** [comment]
aCommand1 (ASCII Command 1)= 'Hello'
and
aCommand2 (ASCII Command 2)= 'How'

ASCII strings of command in data.asm.
You can include command in code.asm.

//Code-------------------------------------------------------------
    aStrCmpF aBuff,aCommand#
    jne not_command#
Command#:
    //What are you want?
    jmp Command
not_command#:
//---------------------------------------------------------------------

It's a very simple code. You can easy modify this.

**Comment by IonicaBizau** [comment]
Nice! Is it possible to build an iso file and use it in Virtual Box?

**Comment by Maneevao** [comment]
Of course, You should just rename file. You can use this like floppy disk(It's same size). But I can't remember everything, I may make a mistake.

**Comment by IonicaBizau** [comment]
I tried it but it says "No bootable device found".

**Comment by Maneevao** [comment]
Yes, I'm sorry. I tried it again. And It really don't make iso file.
Next project ("USBList") don't make iso also.
"OS" make floppy disk.
"USBList" make hard drive.
I don't know information to make iso file.

**Comment by IonicaBizau** [comment]
Ok. Probably some day I will try to build an OS too. :smile: Thanks!
